### ISSUE TITLE
CDN API update

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/website#151]
CDN77 has migrated to a new API, version 3, and we need to update pmaweb/cdn.py to upgrade. The daily snapshots and website updates are affected by this.

https://client.cdn77.com/support/api-docs/v3/migration-guide

**Comment by williamdes** [comment]
Hi @ibennetch 
I implemented it and tested it with my account.
Could you generate a token for phpMyAdmin and fill the `settings.py` file ?
I hope everything will work like on my tests

**Comment by ibennetch** [comment]
Yeah, the token is already present so this seems to just work since your changes. Nice work, thank you!

**Comment by williamdes** [comment]
> Yeah, the token is already present so this seems to just work since your changes. Nice work, thank you!

Thank you !
There was a typo in the config file, but it seems that the files CDN Id `FILES_CDN_ID` is wrong because it outputs a 404. Could you check ?
```
+ ./manage.py import_files
Updated 5.2+snapshot
Updated 5.1+snapshot
Updated 5.3+snapshot
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/builder/website/files/management/commands/import_files.py", line 151, in handle
    self.process_snapshots(os.path.join(settings.FILES_PATH, 'snapshots'))
  File "/home/builder/website/files/management/commands/import_files.py", line 147, in process_snapshots
    purge_files_cdn(*purge)
  File "/home/builder/website/pmaweb/cdn.py", line 69, in purge_files_cdn
    return perform(URL.replace('{id}', settings.FILES_CDN_ID), pages)
  File "/home/builder/website/pmaweb/cdn.py", line 44, in perform
    handle = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by ibennetch** [comment]
Yes, I think the ID changed silently but fixed it shortly after you pushed your work. I think it's been fine since then and haven't seen any errors since I corrected it. Please let me know if you see ongoing failures.

**Comment by williamdes** [comment]
We where probably in sync, I changed the Id on the server and posted the edit to my message above just now ^^

**Comment by williamdes** [comment]
So there is only the git trick to do on the server, the website is updating snapshots correctly now
